<?php

namespace Database\Seeders;

use App\Models\MapRegion;
use Illuminate\Database\Seeder;

class MapRegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $regions = [
            [
                'state_key' => 'state-jammu-kashmir',
                'name' => 'Jammu & Kashmir',
                'type' => 'UT',
                'region' => 'North',
                'tradition' => 'Sufiana Mausiqi mystical tradition, Chakri folk ensembles, Henzae devotional songs.',
                'instruments' => 'Santoor, Rabab, Sarangi, Tumbaknari',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-ladakh',
                'name' => 'Ladakh',
                'type' => 'UT',
                'region' => 'North',
                'tradition' => 'Buddhist monastic chant traditions, ceremonial Daman-Surna ensembles, Dung-chen long horn rituals.',
                'instruments' => 'Daman, Surna, Dung-chen, Damaru',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-himachal-pradesh',
                'name' => 'Himachal Pradesh',
                'type' => 'State',
                'region' => 'North',
                'tradition' => 'Pahari folk and Naati dance traditions echoing across Himalayan valleys.',
                'instruments' => 'Dhol, Ranasingha, Karnal, Shehnai',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-punjab',
                'name' => 'Punjab',
                'type' => 'State',
                'region' => 'North',
                'tradition' => 'Bhangra and Gidda foundations, Sufi Qawwali, Heer Ranjha balladry.',
                'instruments' => 'Dhol, Tumbi, Algoza, Chimta',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-chandigarh',
                'name' => 'Chandigarh',
                'type' => 'UT',
                'region' => 'North',
                'tradition' => 'Modern Punjabi-fusion bridge — where folk meets Indo-electronic and indie.',
                'instruments' => 'Dhol, Tumbi (modern processed)',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-haryana',
                'name' => 'Haryana',
                'type' => 'State',
                'region' => 'North',
                'tradition' => 'Ragini ballads and Saang folk theatre, robust open-throat singing styles.',
                'instruments' => 'Dholak, Been, Sarangi, Ghara',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-delhi',
                'name' => 'Delhi',
                'type' => 'UT',
                'region' => 'North',
                'tradition' => 'Hindustani classical capital, Nizamuddin Qawwali tradition, Delhi gharana.',
                'instruments' => 'Tabla, Sarangi, Harmonium, Sitar',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-uttarakhand',
                'name' => 'Uttarakhand',
                'type' => 'State',
                'region' => 'North',
                'tradition' => 'Garhwali and Kumaoni folk, Jagar invocations of Devbhoomi.',
                'instruments' => 'Dhol-Damau, Hudka, Ransingha',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-uttar-pradesh',
                'name' => 'Uttar Pradesh',
                'type' => 'State',
                'region' => 'North',
                'tradition' => 'Banaras gharana classical, Thumri romantic tradition, Khayal foundations.',
                'instruments' => 'Tabla, Sarangi, Shehnai, Pakhawaj',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-rajasthan',
                'name' => 'Rajasthan',
                'type' => 'State',
                'region' => 'West',
                'tradition' => 'Manganiyar and Langa hereditary musician traditions of the Thar desert.',
                'instruments' => 'Kamaicha, Khartal, Morchang, Sarangi',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-gujarat',
                'name' => 'Gujarat',
                'type' => 'State',
                'region' => 'West',
                'tradition' => 'Garba and Dandiya Raas festival traditions, Sugam Sangeet, Bhavai theatre music.',
                'instruments' => 'Dhol, Manjira, Ravanhatta, Surando',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-dnhdd',
                'name' => 'Dadra & Nagar Haveli and Daman & Diu',
                'type' => 'UT',
                'region' => 'West',
                'tradition' => 'Coastal Konkani-Portuguese fusion traditions, Ghumat-driven festival music.',
                'instruments' => 'Ghumat, Mando ensemble',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-madhya-pradesh',
                'name' => 'Madhya Pradesh',
                'type' => 'State',
                'region' => 'Central',
                'tradition' => 'Malwa folk heritage, Bundelkhandi traditions, central India tribal music.',
                'instruments' => 'Bansuri, Dhol, Mandal, Algoza',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-chhattisgarh',
                'name' => 'Chhattisgarh',
                'type' => 'State',
                'region' => 'Central',
                'tradition' => 'Pandvani epic narration, Panthi devotional, deep Bastar tribal traditions.',
                'instruments' => 'Tambura, Mandar, Dhol, Tasa',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-bihar',
                'name' => 'Bihar',
                'type' => 'State',
                'region' => 'East',
                'tradition' => 'Sohar birth songs, Chhath geet sun rituals, Bhojpuri folk traditions.',
                'instruments' => 'Dholak, Pakhawaj, Harmonium, Khanjari',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-arunachal-pradesh',
                'name' => 'Arunachal Pradesh',
                'type' => 'State',
                'region' => 'Northeast',
                'tradition' => 'Tribal chant traditions of Adi, Apatani, Nyishi communities — sacred and communal.',
                'instruments' => 'Dhol, Bamboo flutes, Gongs',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-assam',
                'name' => 'Assam',
                'type' => 'State',
                'region' => 'Northeast',
                'tradition' => 'Bihu festival music, Borgeet devotional, Sattriya temple traditions.',
                'instruments' => 'Dhol, Pepa, Khol, Taal',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-sikkim',
                'name' => 'Sikkim',
                'type' => 'State',
                'region' => 'Northeast',
                'tradition' => 'Tamang Selo folk, Buddhist monastic chanting, Lepcha traditions.',
                'instruments' => 'Damphu, Dungchen, Yarka',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-meghalaya',
                'name' => 'Meghalaya',
                'type' => 'State',
                'region' => 'Northeast',
                'tradition' => 'Khasi, Garo and Jaintia folk — distinct vocal and instrumental tribal traditions.',
                'instruments' => 'Duitara, Marynthing, Ksing, Tangmuri',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-nagaland',
                'name' => 'Nagaland',
                'type' => 'State',
                'region' => 'Northeast',
                'tradition' => 'Naga choral polyphony, ceremonial log-drum announcements, warrior chants.',
                'instruments' => 'Log drum, Tati, Bamboo mouth organ',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-manipur',
                'name' => 'Manipur',
                'type' => 'State',
                'region' => 'Northeast',
                'tradition' => 'Manipuri Sankirtan devotional ensembles, Pung Cholom drum-dance traditions.',
                'instruments' => 'Pung, Pena, Esraj, Karthal',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-tripura',
                'name' => 'Tripura',
                'type' => 'State',
                'region' => 'Northeast',
                'tradition' => 'Tripuri tribal folk songs, Hojagiri dance music heritage.',
                'instruments' => 'Sarinda, Khamb, Sumui, Chongpreng',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-mizoram',
                'name' => 'Mizoram',
                'type' => 'State',
                'region' => 'Northeast',
                'tradition' => 'Mizo choral harmony traditions, Cheraw bamboo dance percussion.',
                'instruments' => 'Khuang, Bamboo poles, Tumphit',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-jharkhand',
                'name' => 'Jharkhand',
                'type' => 'State',
                'region' => 'East',
                'tradition' => 'Tribal Jhumar dance music, Santhali traditional ensembles.',
                'instruments' => 'Madal, Nagada, Banam, Dhamsa',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-west-bengal',
                'name' => 'West Bengal',
                'type' => 'State',
                'region' => 'East',
                'tradition' => 'Rabindra Sangeet, Baul mystic wandering tradition, classical-folk fusion heritage.',
                'instruments' => 'Ektara, Khamak, Dotara, Tabla',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-odisha',
                'name' => 'Odisha',
                'type' => 'State',
                'region' => 'East',
                'tradition' => 'Odissi temple classical, Pala devotional, Chhau martial dance music.',
                'instruments' => 'Mardala, Mohuri, Khanjani, Ghanta',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-maharashtra',
                'name' => 'Maharashtra',
                'type' => 'State',
                'region' => 'West',
                'tradition' => 'Lavani provocative folk, Abhang devotional, Koli fishermen songs, Powada balladry.',
                'instruments' => 'Dholki, Sambal, Tuntuna, Tabla',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-goa',
                'name' => 'Goa',
                'type' => 'State',
                'region' => 'West',
                'tradition' => 'Mando romantic ballads, Dulpod dance songs, Konkani folk heritage.',
                'instruments' => 'Ghumat, Violin, Mandolin, Cantaram',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-telangana',
                'name' => 'Telangana',
                'type' => 'State',
                'region' => 'South',
                'tradition' => 'Bathukamma flower festival music, Lambadi tribal traditions, Deccan folk heritage.',
                'instruments' => 'Dappu, Tambura, Dolu, Pamba',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-andhra-pradesh',
                'name' => 'Andhra Pradesh',
                'type' => 'State',
                'region' => 'South',
                'tradition' => 'Carnatic classical, Burrakatha narrative ballads, Harikatha devotional storytelling.',
                'instruments' => 'Veena, Mridangam, Tambura, Ghatam',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-karnataka',
                'name' => 'Karnataka',
                'type' => 'State',
                'region' => 'South',
                'tradition' => 'Carnatic classical heartland, Yakshagana coastal theatre, Janapada folk traditions.',
                'instruments' => 'Veena, Mridangam, Chande, Nadaswaram',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-tamil-nadu',
                'name' => 'Tamil Nadu',
                'type' => 'State',
                'region' => 'South',
                'tradition' => 'Carnatic classical authority, Folk Parai percussion traditions, Bharatanatyam temple music.',
                'instruments' => 'Mridangam, Nadaswaram, Veena, Parai',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-puducherry',
                'name' => 'Puducherry',
                'type' => 'UT',
                'region' => 'South',
                'tradition' => 'French-Tamil colonial fusion, Carnatic foundations, coastal devotional music.',
                'instruments' => 'Mridangam, Nadaswaram, Violin',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-kerala',
                'name' => 'Kerala',
                'type' => 'State',
                'region' => 'South',
                'tradition' => 'Sopanam temple tradition, Mappila Muslim folk, Kathakali classical theatre music.',
                'instruments' => 'Chenda, Idakka, Maddalam, Edakka',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-lakshadweep',
                'name' => 'Lakshadweep',
                'type' => 'UT',
                'region' => 'Islands',
                'tradition' => 'Lava dance ceremonial music, Kolkali stick-dance traditions of the Arabian Sea atolls.',
                'instruments' => 'Dholak, Daff, Tabla',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
            [
                'state_key' => 'state-andaman-nicobar',
                'name' => 'Andaman & Nicobar Islands',
                'type' => 'UT',
                'region' => 'Islands',
                'tradition' => 'Nicobarese tribal traditions, Onge and Jarawa indigenous heritage, ocean-rooted rhythms.',
                'instruments' => 'Bamboo flutes, Coconut shell percussion',
                'library_url' => '/shop',
                'collab_url' => '/collaboration',
            ],
        ];

        foreach ($regions as $region) {
            MapRegion::updateOrCreate(['state_key' => $region['state_key']], $region);
        }
    }
}
