<?php

namespace Database\Seeders;

use App\Models\SuccessStory;
use Illuminate\Database\Seeder;

class SuccessStorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $stories = [
            [
                'name' => 'A.R. Rahman',
                'role' => 'Oscar · BAFTA · Golden Globe · Slumdog Millionaire',
                'teaser' => 'Has publicly noted his support for our mission to bring rare Indian virtual instruments to composers worldwide.',
                'quote' => 'Very intrigued by this — wishing you the best.',
                'card_quote' => 'Very intrigued by this — wishing you the best.',
                'image_path' => 'frontend/assets/img/ar_rehman.png',
                'youtube_id' => null,
                'credits' => ['Slumdog Millionaire', 'Roja', '127 Hours', 'Rang De Basanti'],
                'note' => 'Support noted publicly. Crypto Cipher instruments have featured across a number of productions in this circle.',
                'sort_order' => 0,
            ],
            [
                'name' => 'Jörg Hüttner',
                'role' => 'The Dark Knight Rises · Fifty Shades of Grey · White House Down',
                'teaser' => 'Trying out Crypto Cipher sample libraries which I really like — great sounding and super useful across productions.',
                'quote' => "I'm trying out Crypto Cipher sample libraries which I really like. They are really great sounding and super useful in various productions, with a simple but really useful interface in Kontakt. My favourites here are the Tongue Drum, Swarmandal and Tabla. Pretty much all of it is genuinely useful — go ahead and check them out, they're worth it.",
                'card_quote' => 'Great sounding and super useful across productions.',
                'image_path' => 'frontend/assets/img/JORG_HUTTNER.png',
                'youtube_id' => 'bKdvio9KrH4',
                'credits' => ['The Dark Knight Rises', 'The Girl on the Train', 'Independence Day: Resurgence', 'Vantage Point'],
                'note' => null,
                'sort_order' => 1,
            ],
            [
                'name' => 'Nainita Desai',
                'role' => 'BAFTA · Emmy · Oscar winning & nominated film and TV',
                'teaser' => 'Using great Indian talent from all over the country — no other company is doing quite what you do.',
                'quote' => 'Crypto Cipher is using great Indian talent from all over the country. There is no other company out there doing quite what you do. Please keep up the good work producing more unusual libraries that are so inspiring to us — film and television composers, especially out here in the West.',
                'card_quote' => 'No other company is doing quite what you do.',
                'image_path' => 'frontend/assets/img/NAINITA_DESAI.png',
                'youtube_id' => 'k73ufpnk1Sw',
                'credits' => ['For Sama', 'The Reason I Jump', 'American Murder', 'BBC Proms'],
                'note' => null,
                'sort_order' => 2,
            ],
            [
                'name' => 'John Swihart',
                'role' => 'Grammy nominated · How I Met Your Mother · Napoleon Dynamite',
                'teaser' => 'Loving these new libraries — the Tabla is very playable, Swarmandal sounds amazing, Dholak is amazing.',
                'quote' => "I'm sitting with some Crypto Cipher samples and really loving these new libraries. The Tabla is very playable, Swarmandal sounds amazing — just a beautiful sound — and the Dholak is amazing. The loops are great. I'm just loving working with them; they come with great options. Very happy, and I hope you enjoy them too.",
                'card_quote' => 'Loving these new libraries — the Tabla is so playable.',
                'image_path' => null,
                'youtube_id' => 'g3mPqE9T8H4',
                'credits' => ['How I Met Your Mother', 'Napoleon Dynamite', 'Youth in Revolt', 'Employee of the Month'],
                'note' => null,
                'sort_order' => 3,
            ],
            [
                'name' => 'BT',
                'role' => 'Grammy nominated producer · Fast & Furious · Monster',
                'teaser' => 'Absolutely freaking out on these sample libraries. If you\'re looking for unusual Kontakt libraries — check them.',
                'quote' => "Absolutely freaking out on these sample libraries. If you're looking for unusual Kontakt libraries, check out Crypto Cipher.",
                'card_quote' => 'Absolutely freaking out on these sample libraries.',
                'image_path' => null,
                'youtube_id' => null,
                'credits' => ['Fast & Furious', 'Partysaurus Rex', 'Go', 'Stealth', 'Monster'],
                'note' => null,
                'sort_order' => 4,
            ],
            [
                'name' => 'Shankar Tucker',
                'role' => 'Music producer · artist · 140k+ YouTube subscribers',
                'teaser' => 'Please keep making cool libraries — especially loop libraries at the quality you used for Dholak Loops.',
                'quote' => "Good job, Crypto Cipher. Please keep making cool libraries, especially loop libraries at the level of quality you used for the Dholak Loops. I'll definitely be getting the next one.",
                'card_quote' => 'Please keep making cool libraries at this quality.',
                'image_path' => null,
                'youtube_id' => 'Pv4nrDuL-Sk',
                'credits' => ['The ShrutiBox', 'Filmi Collaborations', 'YouTube Originals'],
                'note' => null,
                'sort_order' => 5,
            ],
            [
                'name' => 'Sanchit Balhara',
                'role' => 'Bollywood composer · Bajirao Mastani · Ram-Leela',
                'teaser' => 'Doing really a great job bringing the revolution at world level — I wish them all the best.',
                'quote' => 'Crypto Cipher is doing really, really a great job in bringing the revolution at world level, and I wish them all the best.',
                'card_quote' => 'Bringing the revolution at world level.',
                'image_path' => null,
                'youtube_id' => 'wPSymhkP5a0',
                'credits' => ['Bajirao Mastani', 'Goliyon Ki Raasleela Ram-Leela'],
                'note' => null,
                'sort_order' => 6,
            ],
            [
                'name' => 'Michael Maas',
                'role' => 'Trailer music · The Amazing Spider-Man 2 · Maze Runner',
                'teaser' => 'Hired Crypto Cipher for live sitar recordings from India — sound quality and performance beyond what I imagined.',
                'quote' => 'Crypto Cipher is a really great company. In 2014 I had to record and organise a world-music album for a production library in France, with live solo performances from across the world. For three tracks we needed live sitar from a real, gifted Indian player. I hired Crypto Cipher directly from India and they did a really great job — I never imagined a sound quality and performance like the one they gave us. I highly recommend the company\'s services and plugins.',
                'card_quote' => 'Sound quality and performance beyond what I imagined.',
                'image_path' => 'frontend/assets/img/MICHEAL_MAAS.png',
                'youtube_id' => 'g3mPqE9T8H4',
                'credits' => ['The Amazing Spider-Man 2', 'Chappie', 'Maze Runner', 'The Walking Dead S5'],
                'note' => null,
                'sort_order' => 7,
            ],
            [
                'name' => 'Tim Johnson',
                'role' => 'Sound design · Red Bull Air Race · Project CARS',
                'teaser' => 'Crypto Cipher action walkthrough — a sound designer\'s look at the libraries in use.',
                'quote' => 'A Crypto Cipher action walkthrough video by Tim Johnson — a working sound designer\'s look at the libraries in real use.',
                'card_quote' => 'A go-to for authentic, characterful sound design.',
                'image_path' => null,
                'youtube_id' => '7mHg-vGcP5s',
                'credits' => ['Red Bull Air Race (Oculus Rift)', 'Xbox One Release', 'Project CARS'],
                'note' => null,
                'sort_order' => 8,
            ],
            [
                'name' => 'Pete Lockett',
                'role' => 'Ethnic percussion · last five James Bond films',
                'teaser' => 'Quite a versatile set of instruments — definitely worth checking out. Bringing them into my own productions.',
                'quote' => "It's quite a versatile set of instruments — definitely worth checking out Crypto Cipher. I'm sure they've got new stuff coming soon as well. I'm going to bring them into some of my own productions.",
                'card_quote' => 'A versatile set of instruments — worth checking out.',
                'image_path' => 'frontend/assets/img/pete_lockett.png',
                'youtube_id' => 'xSt5fZ9QBB8',
                'credits' => ['James Bond (×5)', 'Björk', 'Peter Gabriel', 'Robert Plant', 'Jeff Beck'],
                'note' => null,
                'sort_order' => 9,
            ],
            [
                'name' => 'Adriano Clemente',
                'role' => 'Dubspot director',
                'teaser' => 'Interesting to see what solutions people can come up with using these libraries — get out of your usual set of tools.',
                'quote' => "One thing I never get tired of reminding students is the idea of trying to get out of your usual set of tools and sounds. It's really interesting to see what kind of solutions people can come up with using these libraries.",
                'card_quote' => 'Interesting to see what people create with these.',
                'image_path' => null,
                'youtube_id' => 'yzggNxA5jX8',
                'credits' => ['Dubspot', 'Sound Design Education'],
                'note' => null,
                'sort_order' => 10,
            ],
            [
                'name' => 'Laurent Zillani',
                'role' => 'Resident Evil 6 · Priest · Sinister',
                'teaser' => 'A great collection of Indian instruments and sound design — Solo Tabla and Solo Dholak are beautifully recorded.',
                'quote' => "It's a great collection of Indian instruments and sound design. I particularly like the Solo Tabla and Solo Dholak, which I think are beautifully recorded and give you a lot of options.",
                'card_quote' => 'Beautifully recorded — Solo Tabla and Dholak shine.',
                'image_path' => null,
                'youtube_id' => 'UvyzjeBK-es',
                'credits' => ['Resident Evil 6', 'Priest', 'Drag Me to Hell', 'Sinister'],
                'note' => null,
                'sort_order' => 11,
            ],
            [
                'name' => 'K.J. Singh',
                'role' => 'Sound engineer · A.R. Rahman · Vishal Bhardwaj · Amit Trivedi',
                'teaser' => 'Great pains taken to record high-quality sounds with very talented musicians and deep, authentic programming.',
                'quote' => 'The team at Crypto Cipher has taken great pains to record some high-quality sounds. They\'ve got very talented musicians playing these instruments, and some deep programming has gone into making them playable and as authentic as possible.',
                'card_quote' => 'High quality sounds, deeply and authentically programmed.',
                'image_path' => null,
                'youtube_id' => '3Iq6vH5Q7zw',
                'credits' => ['Rang De Basanti', 'Guru', 'Omkara', 'Delhi-6', 'Robot'],
                'note' => null,
                'sort_order' => 12,
            ],
            [
                'name' => 'David Buckley',
                'role' => 'The Town · Batman: Arkham Knight · Call of Duty: Ghosts',
                'teaser' => 'Recorded and programmed with such care — a different league to most other ethnic sample libraries.',
                'quote' => 'I love the samples from Crypto Cipher. They have been recorded and programmed with such care and attention to detail. They stand in a different league to most other ethnic sample libraries because they offer something authentic. Whenever I delve into music from India — or many other places — I instinctively start clicking through the Crypto Cipher folder to see what treasures can be added to my music.',
                'card_quote' => 'A different league to most other ethnic libraries.',
                'image_path' => null,
                'youtube_id' => null,
                'credits' => ['The Town', 'Batman: Arkham Knight', 'Call of Duty: Ghosts', 'The Good Wife'],
                'note' => null,
                'sort_order' => 13,
            ],
        ];

        foreach ($stories as $story) {
            SuccessStory::create($story + ['is_active' => true]);
        }
    }
}
